/*
 * This project was generated by the Ignition Module Generator.  It is intended to provide initial project structure
 * and minimize boilerplate.  This initial project is a starting point for your own module projects using the Gradle
 * build system.  It is not intended to be a replacement for learning and understanding Gradle.
 *
 * Generator: https://github.com/inductiveautomation/ignition-module-tools/tree/master/generator/generator-core
 * Gradle Docs: https://docs.gradle.org/current/userguide/userguide.html
 */

plugins {
    id("io.ia.sdk.modl") version("0.5.0")
}

/*
 * Which Ignition line this build is for: 8.3 (the default) or 8.1.
 *
 *     ./gradlew build                       -> build/designer-dark-mode.modl
 *     ./gradlew build -Pignition.line=8.1   -> build/designer-dark-mode-8.1.modl
 *
 * One source tree, two .modl files, because no single requiredIgnitionVersion
 * is accepted by both lines. Checked against the gateways themselves: 8.3's
 * ModuleInstance refuses any module whose required MAJOR.MINOR differs from
 * its own (ModuleManager.MajorVersionMismatch), and 8.1 refuses any module
 * that requires more than it is ("requires at least"). The only value both
 * accept is the literal "dev", which skips the check altogether; that is an
 * internal mechanism, and it would also let a Java 11 gateway (8.1.25 and
 * older) install a module whose Designer jar needs Java 17.
 *
 * The code is the same for both. It links against either line's jars with
 * nothing missing (the one API that moved, a project's getResource, is looked
 * up by reflection in ExchangeScript), so the line only decides the floor the
 * module compiles against and declares, the file name, and what the harness
 * runs against.
 */
val ignition_line by extra((project.findProperty("ignition.line") as String?) ?: "8.3")
val is_8_1_line = when (ignition_line) {
    "8.3" -> false
    "8.1" -> true
    else -> throw GradleException("ignition.line must be 8.3 or 8.1, not '$ignition_line'")
}

/*
 * The support FLOOR per line. 8.1.33 is the first 8.1 whose Designer runs on
 * Java 17 (8.1.25 and earlier ship Java 11 bytecode), which this module needs.
 */
val sdk_version by extra(if (is_8_1_line) "8.1.33" else "8.3.0")

/*
 * What the HEADLESS HARNESS runs against, which is deliberately not
 * sdk_version (#53).
 *
 * sdk_version is the support FLOOR: it is what the module compiles against, so
 * that a newer API cannot creep in by accident, and it is what goes into
 * module.xml as requiredIgnitionVersion. Neither should follow the latest
 * release.
 *
 * The harness has the opposite job. It exists to catch the module's reflective
 * reach — class, field and method names that no compiler checks — breaking
 * against the Ignition people actually run, and pinned to the floor it was
 * testing jars nobody has. Nothing about the floor is wrong; it is simply not
 * evidence about 8.3.6 or 8.3.8, which is where the reports come from.
 *
 * Override to reproduce a specific gateway: -Pharness.sdk=8.3.6 (on the 8.1
 * line, -Pignition.line=8.1 -Pharness.sdk=8.1.50).
 */
val harness_sdk_version by extra(
    (project.findProperty("harness.sdk") as String?)
        // 8.1.55 is the newest 8.1 whose jars are on IA's Nexus; 8.1.56 has
        // metadata but no files.
        ?: if (is_8_1_line) "8.1.55" else "8.3.8")

allprojects {
    // The release workflow passes -PreleaseVersion=<tag> (the git tag drives the
    // module version — see .github/workflows/release.yml). Local and main-branch
    // builds carry a SNAPSHOT so a dev .modl is never mistaken for a release.
    version = (project.findProperty("releaseVersion") as String?)?.removePrefix("v") ?: "0.0.1-SNAPSHOT"
}

ignitionModule {
    /*
     * Human readable name of the module, as will be displayed on the gateway status page
     */
    name.set("Designer Dark Mode")

    /*
     * Name of the '.modl' file to be created, without file extension.
     */
    fileName.set(if (is_8_1_line) "designer-dark-mode-8.1" else "designer-dark-mode")
    /*
     * Unique identifier for the module.  Reverse domain convention is recommended (e.g.: com.mycompany.charting-module)
     */
    id.set("com.mustrysolutions.designerdarkmode")

    /*
     * Version of the module.  Here being set to the same version that gradle uses, up above in this file.
     */
    moduleVersion.set("${project.version}")

    moduleDescription.set("A dark theme for the Ignition Designer, toggled from Tools -> Dark Mode. Free, by Mustry Solutions (mustrysolutions.com).")

    /*
     * Minimum version of Ignition required for the module to function correctly.  This typically won't change over
     * the course of a major Ignition (7.9, 8.0, etc) version, except for when the Ignition Platform adds/changes APIs
     * used by the module.
     */
    requiredIgnitionVersion.set(sdk_version)
    /*
     *  This is a map of String: String, where the 'key' represents the fully qualified path to the project
     *  (using gradle path syntax), and the value is the shorthand Scope string.
     *  Example entry: listOf( ":gateway" to "G", ":common" to "GC", ":vision-client" to "C" )
     */
    projectScopes.putAll(mapOf(
        ":designer" to "D",
        ":gateway" to "G"
    ))

    /*
     * Add required module dependencies here, following the examples, with scope being one or more of G, C or D,
     * for (G)ateway, (D)esigner, Vision (C)lient.
     *
     * Example:
     *   moduleDependencySpecs {
     *      register("com.inductiveautomation.vision") {
     *          scope = "GCD"
     *          required = true
     *      }
     *      // register("com.another.mod") { ...
     *   }
     *
     * If any of module's required module dependencies are not present, the
     * gateway will fault on loading the module.
     *
     * NOTE: For modules targeting Ignition 8.3 and later. Use `moduleDependencies` for 8.1 and earlier.
     * This property will only add the "required" flag if {requiredIgnitionVersion} is at least 8.3
     *
     */
    moduleDependencySpecs { }

    /*
     * Map of fully qualified hook class to the shorthand scope.  Only one scope may apply to a class, and each scope
     * must have no more than single class registered.  You may omit scope registrations if they do not apply.
     *
     * Example entry: "com.myorganization.vectorizer.VectorizerDesignerHook" to "D"
     */
    hooks.putAll(mapOf(
        "com.mustrysolutions.designerdarkmode.designer.DesignerDarkModeHook" to "D",
        "com.mustrysolutions.designerdarkmode.gateway.DesignerDarkModeGatewayHook" to "G"
    ))

    /*
     * EULA shown by the gateway when the module is installed. The plugin stages
     * this file into the .modl and emits the <license> element in module.xml —
     * no hand-rolled assembleModlStructure/zipModule wiring is needed.
     */
    license.set("license.html")

    /*
     * Apache-2.0 and free: no trial period, no activation, no per-gateway fee.
     * A free module still states its terms via `license` above, it just doesn't
     * opt into the platform's trial/licensing machinery.
     *
     * This writes <freeModule>true</freeModule> into module.xml, which the 8.3
     * gateway does NOT read (#114). What it does read is
     * GatewayModuleHook.isFreeModule() on the gateway-scope hook, which is the
     * whole reason DesignerDarkModeGatewayHook exists. Kept for the record and
     * for any gateway that starts honouring the element.
     */
    freeModule.set(true)

    /*
     * Optional 'documentation' settings.  Supply the files that would be desired to end up in the 'doc' dir of the
     * assembled module, and specify the path to the index.html file inside that folder. In this commented-out
     * example, the html files being collected are located in the module root project in `src/docs/`
     */
    // the files to collect into the documentation dir, with example implementation
    // documentationFiles.from(project.file("src/docs/"))

    /* The path from the root documentation dir to the index file, or filename if in the root doc dir. */
    // documentationIndex.set("index.html")

    /*
     * Optional unsigned modl settings. If true, modl signing will be skipped. This is not for production and should
     * be used merely for development testing
     */
    /*
     * Sign the module only when signing credentials are supplied via -Pignition.signing.*
     * (the ops/ dev scripts pass them, pointing at a local self-signed dev keystore).
     * A plain `./gradlew build` with no signing properties stays unsigned.
     */
    skipModlSigning.set(!project.hasProperty("ignition.signing.keystoreFile"))
}
