package com.mustrysolutions.designerdarkmode.designer;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.UIManager;

import com.formdev.flatlaf.FlatDarkLaf;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * An icon that only arrives AFTER the theme pass has run (#60).
 *
 * <p>The icon walk reads {@code getIcon()} once per component. A widget that
 * fills its icon slot lazily therefore keeps stock, light-mode artwork for the
 * rest of the session: nothing runs over it again, because the late-attach
 * watcher fires on {@code COMPONENT_ADDED} and the component was already there.
 *
 * <p>Found on the Perspective component palette's clear-search button, which is
 * JIDE's {@code QuickFilterField$j}. It renders a light-grey circle with a dark
 * X — stock artwork — while the magnifier beside it is correctly light. The
 * module's own debug log had recorded it as {@code icon=-(-1)} (no icon at all)
 * every session, and a probe of the same button later in the session, once
 * there was text to clear, found a 14x14 {@code ImageIcon} on it.
 *
 * <p>Asserted as an EQUIVALENCE — a late icon ends up wearing exactly what the
 * same icon gets when it is present during the walk — rather than on a measured
 * brightness. Which path does the work varies: a button whose icon has no
 * explicit disabled twin gets one generated by Swing, and where that generated
 * twin is no brighter the pair swap is a no-op and the smart invert takes over.
 * Pinning the outcome to one path would pin an implementation detail; pinning it
 * to the early button pins the thing the fix actually promises. The second
 * assertion guards against the pair being vacuous: if the early button came out
 * untouched too, the equivalence would hold trivially and prove nothing.
 */
class LateIconTest {

    private TreeIconRecolorer icons;
    private ThemeManager manager;

    @BeforeEach
    void installStockDesignerLookAndFeel() throws Exception {
        DesignerLookAndFeel.installStock();
        manager = new ThemeManager();
        manager.captureStockLaf();
        icons = new TreeIconRecolorer();
    }

    @AfterEach
    void leaveTheJvmLight() {
        icons.uninstall();
        if (UIManager.getLookAndFeel() instanceof FlatDarkLaf) {
            manager.apply(false);
        }
    }

    @Test
    @DisplayName("a late icon gets the same treatment as one present during the pass")
    void aLateIconIsStillRecolored() {
        Icon stock = darkGlyph();
        // Two identical buttons. One is wearing the icon when the walk runs;
        // the other is given the same icon afterwards, the way JIDE's
        // QuickFilterField fills its clear button once there is text to clear.
        JButton early = new JButton(stock);
        JButton late = new JButton();
        JPanel panel = new JPanel(new java.awt.GridLayout(2, 1));
        panel.add(early);
        panel.add(late);
        panel.setSize(200, 80);

        manager.apply(true);
        icons.installIn(panel);
        icons.recolorButtonIcons(panel);

        assertNull(late.getIcon(),
            "the late button already had an icon during the pass, so this test is "
                + "not exercising the late-arrival path at all");
        assertFalse(java.util.Arrays.equals(render(stock, early), render(early.getIcon(), early)),
            "the button that DID have its icon during the pass was not retouched "
                + "either, so this test would pass without recoloring anything");

        late.setIcon(stock);

        // Compared as PIXELS, not by identity: each button derives its own icon
        // instance, so the two are equal in what they paint and never the same
        // object.
        assertArrayEquals(render(early.getIcon(), early), render(late.getIcon(), late),
            "the icon that arrived after the pass was left stock while the same "
                + "icon present during the pass was themed — this is the palette's "
                + "clear-search button keeping light-mode artwork on a dark field");

        manager.apply(false);
        icons.uninstall();

        assertSame(stock, late.getIcon(),
            "the stock icon was not put back, so the button keeps a dark-mode "
                + "variant all through light mode");
    }

    /** A dark 14x14 glyph, the size and weight of the real clear-search icon. */
    private static Icon darkGlyph() {
        BufferedImage image = new BufferedImage(14, 14, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = image.createGraphics();
        try {
            g2.setColor(new Color(0x30, 0x30, 0x30));
            g2.fillOval(1, 1, 12, 12);
        } finally {
            g2.dispose();
        }
        return new ImageIcon(image);
    }


    /** What an icon actually paints, as ARGB pixels. */
    private static int[] render(Icon icon, java.awt.Component on) {
        int width = Math.max(icon.getIconWidth(), 1);
        int height = Math.max(icon.getIconHeight(), 1);
        BufferedImage image = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = image.createGraphics();
        try {
            icon.paintIcon(on, g2, 0, 0);
        } finally {
            g2.dispose();
        }
        return image.getRGB(0, 0, width, height, null, 0, width);
    }
}
